apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-readiness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: golang-container
        image: kahootali/golang-api
        ports:
        - containerPort: 8080
          name: tcp
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1