apiVersion: apps/v1
kind: Deployment
metadata:
  name: chowkidar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chowkidar
  template:
    metadata:
      labels:
        app: chowkidar
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: /configs/config.yaml
        image: "stakater/chowkidar:v0.0.32"
        imagePullPolicy: IfNotPresent
        name: chowkidar
        volumeMounts:
        - mountPath: /configs
          name: config-volume
      serviceAccountName: chowkidar
      volumes:
      - configMap:
          name: chowkidar
        name: config-volume
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: chowkidar
  name: chowkidar
---
# Source: chowkidar/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: chowkidar
  name: chowkidar
data:
  config.yaml: |-
    controllers:
    - type: pods
      watchcriterion:
        operator: and
        identifiers:
        - resourceExists
        - healthCheckExists
      actions:
      - name: default