apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: 
    app: chowkidar
  name: chowkidar-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: 
    app: chowkidar
  name: chowkidar-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chowkidar-role
subjects:
  - kind: ServiceAccount
    name: chowkidar
    namespace: default
  - kind: ServiceAccount
    name: chowkidar
    namespace: dev
